{% set version = "0.24" %}

package:
  name: isl
  version: {{ version }}

source:
  fn: isl-{{ version }}.tar.xz
  url: https://libisl.sourceforge.io/isl-{{ version }}.tar.xz
  sha256: fcf78dd9656c10eb8cf9fbd5f59a0b6b01386205fe1934b3b287a0a1898145c0
  patches:
    # From https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-isl/isl-0.14.1-no-undefined.patch
    - no_undefined.patch  # [win]
    # https://github.com/conda-forge/isl-feedstock/pull/27#issuecomment-874363957
    - isl-strdup-win.patch  # [win]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("isl", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libtool                # [unix]
    - autotools_clang_conda  # [win]
    - make                   # [unix]

test:
  commands:
    - if not exist %LIBRARY_LIB%\\isl.lib exit 1            # [win]
    - if not exist %LIBRARY_INC%\\isl\\options.h exit 1     # [win]
    - test ! -f "$PREFIX/lib/libisl.a"          # [unix]
    - test -f "$PREFIX/lib/libisl${SHLIB_EXT}"  # [unix]
    - test -d "$PREFIX/include/isl"             # [unix]

about:
  home: http://isl.gforge.inria.fr/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: a thread-safe C library for manipulating sets and relations of integer points bounded by affine constraints.

extra:
  recipe-maintainers:
    - frol
    - isuruf
