{% set version = "0.25" %}
{% set build_num = 1 %}
{% if with_gmp == "False" %}
{% set build_num = build_num + 100 %}
{% endif %}

package:
  name: isl
  version: {{ version }}

source:
  url: https://libisl.sourceforge.io/isl-{{ version }}.tar.xz
  sha256: be7b210647ccadf90a2f0b000fca11a4d40546374a850db67adb32fad4b230d9
  patches:
    # From https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-isl/isl-0.14.1-no-undefined.patch
    - no_undefined.patch  # [win]
    # https://github.com/conda-forge/isl-feedstock/pull/27#issuecomment-874363957
    - isl-strdup-win.patch  # [win]

build:
  number: {{ build_num }}
  string: {{ val_int_type }}_h{{ PKG_HASH }}_{{ build_num }}
  run_exports:
    - isl {{ version }} {{ val_int_type }}_*
  track_features:
    - isl_{{ val_int_type }}   # [val_int_type != "imath32"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libtool                # [unix]
    - autotools_clang_conda  # [win]
    - make                   # [unix]
  host:
    - gmp       # [val_int_type == "gmp"]
  run:

test:
  commands:
    - if not exist %LIBRARY_LIB%\\isl.lib exit 1            # [win]
    - if not exist %LIBRARY_INC%\\isl\\options.h exit 1     # [win]
    - test ! -f "$PREFIX/lib/libisl.a"          # [unix]
    - test -f "$PREFIX/lib/libisl${SHLIB_EXT}"  # [unix]
    - test -d "$PREFIX/include/isl"             # [unix]
    - test ! -f "$PREFIX/include/isl/val_gmp.h"   # [unix and val_int_type != "gmp"]
    - test -f "$PREFIX/include/isl/val_gmp.h"     # [unix and val_int_type == "gmp"]

about:
  home: http://isl.gforge.inria.fr/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: a thread-safe C library for manipulating sets and relations of integer points bounded by affine constraints.

extra:
  recipe-maintainers:
    - frol
    - isuruf
    - inducer
